n = input('digite qualqer porra (pode ser tanto numérico quanto alfabético): ')
print('O tipo primitivo desse valor é: ', type(n))
print('o valor é numérico? ', n.isnumeric())
print('o valor é alfabético? ', n.isalpha())
print('o valor é alfanumérico? ', n.isalnum())
print('o valor esta somente em maiúsculo? ', n.isupper())
print('o valor é um dígito? ', n.isdigit())
print('o valor está somente em minúsculo? ', n.islower())
print('o valor é um identificadr? ', n.isidentifier())
print('o valor é imprimével? ', n.isprintable())
print('o valor é um espaço? ', n.isspace())