frase = 'Curso em Vídeo Python'
print(frase[3])
print(frase[3:13])
print(frase[:13])
print(frase[1:15:2])
print(frase[::2])
print(frase.count('o'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title( ))
print('Curso' in frase)
print(frase.find('Vídeo'))
print(len(frase))
print(frase.replace('Python', 'Android'))
dividido = frase.split()
print(dividido[2])
print(dividido[2][3])